<?php
/**
 * Full Page Cache — server rewrite rules.
 *
 * The optional fastest tier. With these rules in place Apache or LiteSpeed
 * answers a cache hit straight from disk: no PHP process, no drop-in, no
 * WordPress. The difference against the drop-in is roughly 5ms versus 0.2ms per
 * request — irrelevant to a single visitor, decisive under a traffic spike on
 * shared hosting, where PHP worker slots are the thing that actually runs out.
 *
 * ORDERING MATTERS MORE THAN THE RULES DO.
 *
 * WordPress's own block ends with `RewriteRule . /index.php [L]`, which is
 * terminal for any URL that is not a real file. Rules written *after* that block
 * are unreachable. So these are spliced in immediately before `# BEGIN
 * WordPress` by hand rather than appended with insert_with_markers(), which has
 * no concept of position.
 *
 * Everything here is opt-in and reversible, and the rules are written so that
 * any condition failing simply falls through to normal WordPress — a cache miss,
 * never an error page.
 *
 * @package MBRPE
 * @since   2.0.0
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class MBRPE_Page_Cache_Rules {

	const MARKER_START = '# BEGIN MBR Page Cache';
	const MARKER_END   = '# END MBR Page Cache';

	/**
	 * Is this server able to use .htaccess at all?
	 *
	 * @return bool
	 */
	public static function server_supports_htaccess() {
		if ( ! class_exists( 'MBRPE_Server_Headers' ) ) {
			return false;
		}
		return in_array( MBRPE_Server_Headers::detect_server(), array( 'apache', 'litespeed' ), true );
	}

	/**
	 * Path to the site's root .htaccess.
	 *
	 * @return string
	 */
	public static function htaccess_path() {
		if ( ! function_exists( 'get_home_path' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}
		return trailingslashit( get_home_path() ) . '.htaccess';
	}

	/**
	 * Cache directory expressed relative to DOCUMENT_ROOT.
	 *
	 * Returns '' when wp-content sits outside the document root (a bedrock-style
	 * layout, a symlinked deploy). In that case .htaccess serving is simply not
	 * offered — the drop-in still works perfectly.
	 *
	 * @return string e.g. 'wp-content/cache/mbr-performance'
	 */
	public static function relative_cache_path() {
		$doc_root = isset( $_SERVER['DOCUMENT_ROOT'] ) ? sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ) : '';
		$doc_root = $doc_root ? realpath( $doc_root ) : false;
		$cache    = realpath( MBRPE_Page_Cache::cache_dir() );

		if ( ! $doc_root || ! $cache ) {
			return '';
		}

		$doc_root = rtrim( str_replace( '\\', '/', $doc_root ), '/' );
		$cache    = rtrim( str_replace( '\\', '/', $cache ), '/' );

		if ( 0 !== strpos( $cache, $doc_root . '/' ) ) {
			return '';
		}

		return ltrim( substr( $cache, strlen( $doc_root ) ), '/' );
	}

	/**
	 * Are the rules currently installed?
	 *
	 * @return bool
	 */
	public static function are_installed() {
		$path = self::htaccess_path();
		if ( ! file_exists( $path ) ) {
			return false;
		}
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_get_contents
		$contents = @file_get_contents( $path ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		return $contents && false !== strpos( $contents, self::MARKER_START );
	}

	/**
	 * Build the rewrite block.
	 *
	 * @return string
	 */
	public static function build_rules() {
		$rel = self::relative_cache_path();
		if ( '' === $rel ) {
			return '';
		}

		$opts   = mbrpe()->get_options( 'cache' );
		$config = MBRPE_Page_Cache_Dropin::build_config();

		$root = '/' . $rel;
		$file = '%{DOCUMENT_ROOT}' . $root . '/%{ENV:MBRPE_SCHEME}/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:MBRPE_DEVICE}.html';
		$rule = $root . '/%{ENV:MBRPE_SCHEME}/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:MBRPE_DEVICE}.html';

		// Cookie names that must send the request to PHP. Kept in sync with the
		// drop-in's exclude_cookies, minus anything that is not a literal prefix.
		$cookie_parts = array();
		foreach ( (array) $config['exclude_cookies'] as $cookie ) {
			$cookie = trim( (string) $cookie );
			if ( '' !== $cookie && preg_match( '/^[A-Za-z0-9_-]+$/', $cookie ) ) {
				$cookie_parts[] = preg_quote( $cookie, '/' );
			}
		}
		$cookie_regex = $cookie_parts ? implode( '|', $cookie_parts ) : 'wordpress_logged_in_';

		$lines = array();

		$lines[] = self::MARKER_START;
		$lines[] = '# Generated by MBR Performance ' . MBRPE_VERSION . '. Edits are overwritten.';
		$lines[] = '<IfModule mod_rewrite.c>';
		$lines[] = 'RewriteEngine On';
		$lines[] = '';
		$lines[] = '    # --- Resolve the scheme directory --------------------------------';
		$lines[] = '    RewriteCond %{HTTPS} =on [OR]';
		$lines[] = '    RewriteCond %{SERVER_PORT} ^443$ [OR]';
		$lines[] = '    RewriteCond %{HTTP:X-Forwarded-Proto} =https';
		$lines[] = '    RewriteRule .* - [E=MBRPE_SCHEME:https]';
		$lines[] = '    RewriteCond %{ENV:MBRPE_SCHEME} !=https';
		$lines[] = '    RewriteRule .* - [E=MBRPE_SCHEME:http]';
		$lines[] = '';

		if ( ! empty( $config['vary_mobile'] ) ) {
			$lines[] = '    # --- Resolve the device variant ----------------------------------';
			$lines[] = '    RewriteCond %{HTTP_USER_AGENT} "(' . $config['mobile_agents'] . ')" [NC]';
			$lines[] = '    RewriteRule .* - [E=MBRPE_DEVICE:-mobile]';
			$lines[] = '';
		}

		// The shared guard conditions, emitted twice (gzip rule, then plain).
		$guards = self::guard_conditions( $cookie_regex, $config );

		$lines[] = '    # --- Serve the pre-compressed copy where accepted ----------------';
		$lines[] = '    RewriteCond %{HTTP:Accept-Encoding} gzip';
		foreach ( $guards as $guard ) {
			$lines[] = '    ' . $guard;
		}
		$lines[] = '    RewriteCond ' . $file . '.gz -f';
		$lines[] = '    RewriteRule .* ' . $rule . '.gz [L]';
		$lines[] = '';

		$lines[] = '    # --- Serve the plain copy ---------------------------------------';
		foreach ( $guards as $guard ) {
			$lines[] = '    ' . $guard;
		}
		$lines[] = '    RewriteCond ' . $file . ' -f';
		$lines[] = '    RewriteRule .* ' . $rule . ' [L]';
		$lines[] = '</IfModule>';
		$lines[] = '';
		$lines[] = '<IfModule mod_headers.c>';
		$lines[] = '    # The .gz entries are HTML, not a gzip download. Say so explicitly,';
		$lines[] = '    # or browsers offer to save the page instead of rendering it.';
		$lines[] = '    <FilesMatch "\\.html\\.gz$">';
		$lines[] = '        Header set Content-Encoding gzip';
		$lines[] = '        Header set Content-Type "text/html; charset=UTF-8"';
		$lines[] = '        Header append Vary Accept-Encoding';
		$lines[] = '    </FilesMatch>';

		if ( ! empty( $opts['debug_header'] ) ) {
			$lines[] = '    <FilesMatch "index(-[A-Za-z0-9]+)*\\.html(\\.gz)?$">';
			$lines[] = '        Header set X-MBR-Cache "HIT-STATIC"';
			$lines[] = '    </FilesMatch>';
		}

		$lines[] = '</IfModule>';
		$lines[] = self::MARKER_END;

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * The conditions every serving rule must satisfy.
	 *
	 * Each one is a reason to hand the request back to PHP, where the full
	 * decision tree lives. Being over-cautious here costs a few milliseconds;
	 * being under-cautious serves somebody a logged-in page.
	 *
	 * @param string $cookie_regex Alternation of cookie-name prefixes.
	 * @param array  $config       Compiled config.
	 * @return string[]
	 */
	private static function guard_conditions( $cookie_regex, $config ) {
		$conditions = array(
			'RewriteCond %{REQUEST_METHOD} ^(GET|HEAD)$',
			// Any query string at all goes to PHP, which knows which parameters
			// are ignorable and which key their own entry.
			'RewriteCond %{QUERY_STRING} ^$',
			'RewriteCond %{HTTP:Cookie} !(' . $cookie_regex . ') [NC]',
			'RewriteCond %{REQUEST_URI} !^/wp-admin',
			'RewriteCond %{REQUEST_URI} !^/wp-login\\.php',
			'RewriteCond %{REQUEST_URI} !^/wp-cron\\.php',
			'RewriteCond %{REQUEST_URI} !^/wp-json',
			'RewriteCond %{REQUEST_URI} !^/xmlrpc\\.php',
			'RewriteCond %{REQUEST_URI} !^/wp-content',
			'RewriteCond %{REQUEST_URI} !^/wp-includes',
			// Traversal and exotic characters: bail rather than guess.
			'RewriteCond %{REQUEST_URI} !\\.\\.',
			'RewriteCond %{REQUEST_URI} ^[A-Za-z0-9/_.~%-]*$',
		);

		// Honour the site's canonical trailing-slash style, so the rules never
		// swallow the 301 WordPress would otherwise issue.
		if ( isset( $config['trailing_slash'] ) && null !== $config['trailing_slash'] ) {
			$conditions[] = $config['trailing_slash']
				? 'RewriteCond %{REQUEST_URI} /$'
				: 'RewriteCond %{REQUEST_URI} !/$ [OR]' . "\n    " . 'RewriteCond %{REQUEST_URI} ^/$';
		}

		return $conditions;
	}

	/**
	 * Install or refresh the rules.
	 *
	 * @return true|WP_Error
	 */
	public static function install() {
		if ( ! self::server_supports_htaccess() ) {
			return new WP_Error( 'mbrpe_rules_server', __( 'This server does not read .htaccess files, so static serving is not available. The advanced-cache.php drop-in is already doing the heavy lifting.', 'mbr-performance' ) );
		}

		$rules = self::build_rules();
		if ( '' === $rules ) {
			return new WP_Error( 'mbrpe_rules_path', __( 'The cache directory is not inside the document root, so it cannot be addressed by a rewrite rule. Caching still works via the drop-in.', 'mbr-performance' ) );
		}

		$path = self::htaccess_path();

		if ( file_exists( $path ) && ! wp_is_writable( $path ) ) {
			return new WP_Error( 'mbrpe_rules_readonly', __( '.htaccess is not writable. The rules below can be pasted in manually, immediately above the # BEGIN WordPress block.', 'mbr-performance' ) );
		}
		if ( ! file_exists( $path ) && ! wp_is_writable( dirname( $path ) ) ) {
			return new WP_Error( 'mbrpe_rules_nodir', __( 'The site root is not writable, so .htaccess cannot be created.', 'mbr-performance' ) );
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_get_contents
		$contents = file_exists( $path ) ? (string) @file_get_contents( $path ) : ''; // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

		// One-time backup before we ever touch this file.
		if ( '' !== $contents && ! file_exists( $path . '.mbrpe-backup' ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_copy
			@copy( $path, $path . '.mbrpe-backup' ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		}

		$contents = self::strip_block( $contents );

		// Splice in above WordPress's own block, because that block is terminal.
		$position = strpos( $contents, '# BEGIN WordPress' );
		if ( false !== $position ) {
			$contents = substr( $contents, 0, $position ) . $rules . "\n" . substr( $contents, $position );
		} else {
			$contents = $rules . "\n" . $contents;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		if ( false === @file_put_contents( $path, $contents, LOCK_EX ) ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
			return new WP_Error( 'mbrpe_rules_write', __( '.htaccess could not be written.', 'mbr-performance' ) );
		}

		return true;
	}

	/**
	 * Remove the rules.
	 *
	 * @return bool
	 */
	public static function uninstall() {
		$path = self::htaccess_path();
		if ( ! file_exists( $path ) || ! wp_is_writable( $path ) ) {
			return false;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_get_contents
		$contents = (string) @file_get_contents( $path ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		$stripped = self::strip_block( $contents );

		if ( $stripped === $contents ) {
			return true;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		return false !== @file_put_contents( $path, $stripped, LOCK_EX ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
	}

	/**
	 * Remove our marker block from an .htaccess string.
	 *
	 * @param string $contents File contents.
	 * @return string
	 */
	private static function strip_block( $contents ) {
		$pattern = '/' . preg_quote( self::MARKER_START, '/' ) . '.*?' . preg_quote( self::MARKER_END, '/' ) . '\R*/s';
		$result  = preg_replace( $pattern, '', $contents );

		return ( null === $result ) ? $contents : $result;
	}

	/**
	 * Called on deactivation.
	 *
	 * @return void
	 */
	public static function cleanup_on_deactivation() {
		self::uninstall();
	}

	/**
	 * Equivalent Nginx configuration, for display and copying.
	 *
	 * Nginx has no .htaccess, so this has to go in the server block by hand.
	 * Shown rather than written, since a plugin editing nginx.conf would be
	 * both impossible on most hosts and unwise on the rest.
	 *
	 * @return string
	 */
	public static function nginx_snippet() {
		$rel = self::relative_cache_path();
		if ( '' === $rel ) {
			$rel = 'wp-content/cache/mbr-performance';
		}

		$config  = MBRPE_Page_Cache_Dropin::build_config();
		$mobile  = ! empty( $config['vary_mobile'] );
		$variant = $mobile ? '$mbr_device' : '';

		$snippet = "# MBR Performance — full page cache\n"
			. "# Place inside the server { } block, above the main location / block.\n\n"
			. "set \$mbr_cache \"\";\n"
			. "set \$mbr_scheme \"http\";\n"
			. "if (\$http_x_forwarded_proto = \"https\") { set \$mbr_scheme \"https\"; }\n"
			. "if (\$scheme = \"https\") { set \$mbr_scheme \"https\"; }\n\n";

		if ( $mobile ) {
			$snippet .= "set \$mbr_device \"\";\n"
				. "if (\$http_user_agent ~* \"(" . $config['mobile_agents'] . ")\") { set \$mbr_device \"-mobile\"; }\n\n";
		}

		$snippet .= "# Any of these means: hand the request to PHP.\n"
			. "if (\$request_method != GET) { set \$mbr_cache \"skip\"; }\n"
			. "if (\$query_string != \"\") { set \$mbr_cache \"skip\"; }\n"
			. "if (\$http_cookie ~* \"(wordpress_logged_in_|comment_author_|wp-postpass_|woocommerce_items_in_cart|wp_woocommerce_session_)\") { set \$mbr_cache \"skip\"; }\n"
			. "if (\$request_uri ~* \"^/(wp-admin|wp-login\\.php|wp-cron\\.php|wp-json|xmlrpc\\.php)\") { set \$mbr_cache \"skip\"; }\n\n"
			. "location / {\n"
			. "    if (\$mbr_cache = \"skip\") {\n"
			. "        rewrite ^ /index.php last;\n"
			. "    }\n"
			. "    try_files \"/{$rel}/\$mbr_scheme/\$host\$uri/index{$variant}.html\" \$uri \$uri/ /index.php?\$args;\n"
			. "}\n\n"
			. "# Never let anyone browse the cache directly.\n"
			. "location ~ ^/{$rel}/ {\n"
			. "    internal;\n"
			. "}\n";

		return $snippet;
	}
}
